services:
  web:
    image: oscarastua29/frontend:v0.1.0
    depends_on:
      - api
    ports:
      - "8080:3000"
    networks:
      - network-backend
  api:
    image: oscarastua29/backend:v1.0.0
    depends_on:
      - mongo
    ports:
      - "3000:3001"
    networks: 
     - network-backend

  nginx:
    image: nginx
    ports:
      - "443:443"   # Exponiendo el puerto HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks: 
     - network-backend
 
networks:
  network-backend:

volumes: 
  mongodb_data:
